# Generated by Django 4.2.5 on 2024-06-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NightClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.IntegerField(help_text='Duration in weeks')),
                ('time', models.CharField(help_text="Format: '(x)pm - (y)pm'", max_length=20)),
                ('start_date', models.DateField(help_text="Format: 'Weekday Date# CalendarMonth'")),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True, null=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('optional_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('sold_out', models.BooleanField(default=False)),
            ],
        ),
    ]
